# Generated by Django 6.0.3 on 2026-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
